# constants.py

LEAD_CATEGORY_UNCONVERTED = "Unconverted"
LEAD_CATEGORY_NEW = "New"
LEAD_CATEGORY_CONTACTED = "Contacted"
LEAD_CATEGORY_CONVERTED = "Converted"

LEAD_CATEGORIES = {
    LEAD_CATEGORY_UNCONVERTED: LEAD_CATEGORY_UNCONVERTED,
    LEAD_CATEGORY_NEW: LEAD_CATEGORY_NEW,
    LEAD_CATEGORY_CONTACTED: LEAD_CATEGORY_CONTACTED,
    LEAD_CATEGORY_CONVERTED: LEAD_CATEGORY_CONVERTED,
}
