LEAD_CATEGORY_UNCONVERTED = 1
LEAD_CATEGORY_NEW = 2
LEAD_CATEGORY_CONTACTED = 3
LEAD_CATEGORY_CONVERTED = 4

LEAD_CATEGORIES = {
    LEAD_CATEGORY_UNCONVERTED: 'Unconverted',
    LEAD_CATEGORY_NEW: 'New',
    LEAD_CATEGORY_CONTACTED: 'Contacted',
    LEAD_CATEGORY_CONVERTED: 'Converted',
}
