# Generated by Django 5.1 on 2024-08-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('added_date', models.DateTimeField()),
                ('category', models.TextField(default='unconverted')),
            ],
        ),
    ]
