# Generated by Django 5.1 on 2024-09-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_customer_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='total_purchases',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
