# Generated by Django 5.1 on 2024-09-10 18:02

from django.db import migrations, models
from django.contrib.auth.hashers import make_password

def create_default_data(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Admin = apps.get_model('accounts', 'Admin')
    Organization = apps.get_model('accounts', 'Organization')
    Agent = apps.get_model('accounts', 'Agent')

    # Create default organizations
    orgs = []
    for i in range(3):
        org = Organization(
            name=f'Default Organization {i+1}',
            email=f'org{i+1}@example.com',
            website=f'http://exampleorg{i+1}.com',
        )
        org.save()
        orgs.append(org)
    
    # Create default users and admins
    for i in range(3):
        user = User(
            username=f'admin{i+1}',
            first_name=f'AdminFName{i+1}',
            last_name=f'AdminLName{i+1}',
            email=f'admin{i+1}@example.com',
            password=make_password('joekim123'),  
            is_staff=True,
            is_superuser=True,
        )
        user.save()

        # Assign admin to organization
        admin = Admin(
            user=user,
            org=orgs[i % 3]
        )
        admin.save()

        # Create default agents
        for j in range(3):
            agent_user = User(
                username=f'agent{i*3+j+1}',
                first_name=f'AgentFirstName{i*3+j+1}',
                last_name=f'AgentLastName{i*3+j+1}',
                email=f'agent{i*3+j+1}@example.com',
                password=make_password('joekim123'),  
            )
            agent_user.save()

            agent = Agent(
                user=agent_user,
                org=orgs[i % 3]
            )
            agent.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),  # Change this to the name of the last migration file
    ]

    operations = [
        migrations.RunPython(create_default_data),
    ]

