# Generated by Django 5.1 on 2024-08-22 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_lead', to='client.lead'),
        ),
        migrations.AddField(
            model_name='customer',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='agent',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='admin',
            name='org',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='accounts.organization'),
        ),
    ]
