# Generated by Django 5.1 on 2024-09-29 00:46

from django.db import migrations


def create_orgs_and_admins(apps, schema_editor):
    # Get models
    Organization = apps.get_model('accounts', 'Organization')
    User = apps.get_model('accounts', 'User')
    Admin = apps.get_model('accounts', 'Admin')

    # Create 3 organizations
    org1 = Organization.objects.create(
        name='Organization1',
        email='orgg1@example.com',
        address='123 Org One Street',
        phone_number='123-456-7890',
        website='https://org1.com'
    )

    org2 = Organization.objects.create(
        name='Organization2',
        email='orgg2@example.com',
        address='456 Org Two Street',
        phone_number='098-765-4321',
        website='https://org2.com'A
    )

    org3 = Organization.objects.create(
        name='Organization3',
        email='orgg3@example.com',
        address='789 Org Three Road',
        phone_number='555-555-5555',
        website='https://org3.com'
    )


    admin1 = User.objects.create(
        username='adminn1',
        first_name='Admin',
        last_name='One',
        email='adminn1@example.com',
        password='joekim123',
        role=1, 
        is_staff=True,
        is_superuser=True
    )

    admin2 = User.objects.create(
        username='adminn2',
        first_name='Admin',
        last_name='Two',
        email='adminn2@example.com',
        password='joekim123',
        role=1,
        is_staff=True,
        is_superuser=True
    )

    admin3 = User.objects.create(
        username='adminn3',
        first_name='Admin',
        last_name='Three',
        email='adminn3@example.com',
        password='joekim123',
        role=1,
        is_staff=True,
        is_superuser=True
    )

    Admin.objects.create(user=admin1, org=org1)
    Admin.objects.create(user=admin2, org=org2)
    Admin.objects.create(user=admin3, org=org3)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),  
    ]

    operations = [
        migrations.RunPython(create_orgs_and_admins),
    ]
