# Generated by Django 5.1 on 2024-09-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'Admin'), (2, 'Agent'), (3, 'Customer')], default=2),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
